// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyuejcdzjhzafyuxiwze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5dWVqY2R6amh6YWZ5dXhpd3plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMjI5NDMsImV4cCI6MjA2ODg5ODk0M30.OMqqcNqo3_eV9YYUoSYJQjvsUpq8xQk5chIyiDpTkyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});